// src/components/enums/maVaiTro.enum.js
const MaVaiTro = Object.freeze({
  ADMIN_HE_THONG: 'ADMIN_HE_THONG',
  CB_TO_CHUC_SU_KIEN: 'CB_TO_CHUC_SU_KIEN',
  BGH_DUYET_SK_TRUONG: 'BGH_DUYET_SK_TRUONG',
  QUAN_LY_CSVC: 'QUAN_LY_CSVC',
  TRUONG_KHOA: 'TRUONG_KHOA',
  TRUONG_CLB: 'TRUONG_CLB',
  BI_THU_DOAN: 'BI_THU_DOAN',
  SINH_VIEN: 'SINH_VIEN',
  GIANG_VIEN: 'GIANG_VIEN',
});

export default MaVaiTro;
